[[redirects]]
  from = "/history/"
  to = "/pages/history/"
  status = 200

[[redirects]]
  from = "/history/*"
  to = "/pages/history/:splat"
  status = 200

[[redirects]]
  from = "/add-task/*"
  to = "/pages/add-task/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pages/add-task/index.html"
  status = 200

